services:
  client:
    build:
<<<<<<< HEAD
      context: ./client
      dockerfile: ../Dockerfile_client
    command: pnpm run start
=======
      context: ./
      dockerfile: ./Dockerfile_client
    command: pnpm run build
>>>>>>> 089f4d1c5703f36a7ac812b192b01c33819536a2
    working_dir: /app
    tty: true
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
<<<<<<< HEAD
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store

  websocket:
    build:
      context: ./websocket
      dockerfile: ../Dockerfile_websocket
=======
    # ports:
    # - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    entrypoint: bash -c "pnpm install && exec pnpm run build"

  websocket:
    build:
      context: ./
      dockerfile: ./Dockerfile_websocket
>>>>>>> 089f4d1c5703f36a7ac812b192b01c33819536a2
    command: pnpm run dev
    working_dir: /app
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./websocket:/app
<<<<<<< HEAD
      - websocket_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
=======
      - /app/node_modules
    entrypoint: bash -c "pnpm install && exec pnpm run dev"
>>>>>>> 089f4d1c5703f36a7ac812b192b01c33819536a2
  nginx:
    image: nginx
    restart: always
    ports:
<<<<<<< HEAD
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./client/build:/var/www

volumes:
  client_node_modules:
  websocket_node_modules:
  pnpm_store:
=======
            - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./client/build:/var/www
>>>>>>> 089f4d1c5703f36a7ac812b192b01c33819536a2
